language: cpp
notifications:
    email: false
env:
    - JULIAVERSION="stable/linux-i386"
    - JULIAVERSION="stable/linux-x86_64"
    - JULIAVERSION="download/linux-i386"
    - JULIAVERSION="download/linux-x86_64"
before_install:
    - sudo apt-get install libc6:i386 libstdc++6:i386 -y
    - mkdir -p ~/julia
    - curl -L https://status.julialang.org/$JULIAVERSION | tar -C ~/julia --strip-components=1 -x -z -f -
    - export PATH=$PATH:$HOME/julia/bin
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
    - julia -e 'versioninfo(); Pkg.clone(pwd()); Pkg.test("JSON", coverage=true)'
after_success:
    - julia -e 'cd(Pkg.dir("JSON")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
